extends: google
env:
    browser: true

parserOptions:
    ecmaVersion: 2018
    sourceType: "module"

rules: 
    no-tabs: off
    no-unused-vars: off
    max-len: 
        - error
        - code: 100
