plugins:
  - '@typescript-eslint'
extends:
  - google
  - 'plugin:@typescript-eslint/recommended'
env:
  browser: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"

rules:
  no-unused-vars: off
  max-len:
    - error
    - code: 100
  max-lines-per-function:
    - error
    - max: 50
